# DataSource 配置
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql://localhost:3306/vanguard?useUnicode=true&characterEncoding=utf8&autoReconnect=true
      username: root
      password: 13526458168
      initial-size: 2
      min-idle: 2
      max-active: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: admin
        login-password: admin
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 3000
          merge-sql: true

#  mvc:
#    static-path-pattern: /static/**
    view:
      prefix: /templates/
      suffix: .html
    favicon:
      enabled: false
  jmx:
    enabled: false
#  resources:
#    static-locations: classpath:/static
  thymeleaf:
    prefix: classpath:/templates
    suffix: .html

mybatis:
#  type-aliases-package: com.vanguard8.*.core.entity
  mapper-locations: classpath*:mapper/**/*.xml

# log4j2 配置文件位置
logging:
  config: classpath:logback.xml





